### ISSUE TITLE
一个很严重的问题

### ISSUE THREAD

**Issue by ywsswy** [0Chencc/CTFCrackTools#12]
字母宽度不相同
这个很严重
因为多行文本的时候
字母等宽才方便看出字母个数
字母等宽才方便解密一些对齐的文本
字母等宽才方便解密快速找到某位置的字符

**Comment by 0Chencc** [comment]
你好 关于您之前提交过的部分issue 我已经应用于新版：https://github.com/0Chencc/CTFCrackTools/releases/tag/3.1.4
希望您继续使用后加以反馈，谢谢
