### ISSUE TITLE
v3.1.4 朽木师傅版 维吉利亚加解密不好使

### ISSUE THREAD

**Issue by DaPangR** [0Chencc/CTFCrackTools#16]
输入key的窗口弹不出来
![image](https://user-images.githubusercontent.com/7512488/48682444-2ffccb80-ebe3-11e8-94d8-fe9fe03c342c.png)

**Comment by 0Chencc** [comment]
在命令行用java -jar CTFCrackTools.jar运行程序
然后把报错代码贴我看看

**Comment by 0Chencc** [comment]
你好，请你确认一下你的java版本。本程序推荐使用jdk8版本。在jdk9的版本中，因为时间关系，我现在无法处理在jdk9下的一系列bug。等高考结束后，我将会逐个修复
