### ISSUE TITLE
mac上使用时无法复制粘贴

### ISSUE THREAD

**Issue by aa65431362** [0Chencc/CTFCrackTools#19]
mac上使用时无法复制粘贴，麻烦作者大大修复下

**Comment by gh0stkey** [comment]
这个也算是bug，很多jar的都存在，你不妨可以尝试ctrl+c ctrl+v快捷键（widnwos）而不是（mac）的 command+c command+v

**Comment by 0Chencc** [comment]
已解决，请下载新版本
