### ISSUE TITLE
16进制ascii码转字符串

### ISSUE THREAD

**Issue by 7777777line** [0Chencc/CTFCrackTools#2]
你好，今天发现了CTFCrackTools这个工具，体验了一下，在离线的比赛中应该挺有帮助的。
不过使用过程中发现了点问题。
我使用“插件”中的“Base16>>字符串”的功能，这个功能和16进制的ascii码转字符串功能差不多吧。这个插件不能识别小写字母，例如“666c61677b686578327374727d”，转成字符串就是“flag{hex2str}”，但是插件无法转出来，即base64.b16decode()这个方法不能识别小写字母。但是在CTF比赛中这些字符串大小写的情况都可能会出现，所以建议改一下使用的方法？比如使用 binascii.a2b_hex()方法（需导入binascii包），这个方法就是专门将16进制的ascii码转换为字符串。当然，为了代码的工整性，不替换方法，另写一个插件也行 :)

**Comment by 0Linchen** [comment]
好的。我今晚更新

**Comment by 0Linchen** [comment]
好的。我今晚更新

**Comment by 0Linchen** [comment]
对了。。这个工具是可以自己编写插件的。。在工具介绍有IDE

**Comment by 0Linchen** [comment]
老哥 我已经更新完毕了 在Plugin里面 你可以下载后添加插件就行了

**Comment by 0Linchen** [comment]
额....我刚刚直接将插件封包进程序了...等会重新上传封装好的压缩包...老哥你直接下载就行了

**Comment by 0Chencc** [comment]
close
