### ISSUE TITLE
添加插件后生成的json路径不对

### ISSUE THREAD

**Issue by Southseast** [0Chencc/CTFCrackTools#20]
系统是MacOS 10.14.5，添加插件后在CTFCrackToolsKt-3.1.6文件夹外面生成了CTFCrackToolsKt-3.1.6\Setting.json。

**Comment by 0Chencc** [comment]
已修复[78a004e30c07dde3174178cee4b1770f87b94080](https://github.com/0Chencc/CTFCrackTools/commit/78a004e30c07dde3174178cee4b1770f87b94080)
