### ISSUE TITLE
v400加载不了plugin

### ISSUE THREAD

**Issue by littleheary** [0Chencc/CTFCrackTools#34]
我尝试了中文路径和英文路径，加载都没有任何反应。

**Comment by 0Chencc** [comment]
您贴一下setting.json和plugins.json的数据，我看一下。加载plugin需要先将jython加载到工具里，在SettingConfig中。

**Comment by 0Chencc** [comment]
或者让我看一下您的插件，需要def main(input)以及def author_info()这两个函数，才可以正常导入
