### ISSUE TITLE
4.0x版本如何打开

### ISSUE THREAD

**Issue by jyw358** [0Chencc/CTFCrackTools#39]
![1656496509422](https://user-images.githubusercontent.com/41808750/176408798-5fe913d8-9806-4918-8879-fe8bb58d250c.jpg)
4.0.6版本如何运行，是java  -jar  jython-standalone-2.7.2.jar吗，没有成功。文件夹内没有其它jar文件了。

**Comment by 0Chencc** [comment]
下载[releases](https://github.com/0Chencc/CTFCrackTools/releases/)中的CTFCrackTools.zip解压即可
