### ISSUE TITLE
v3.1.1无法将ascii转换为字符串，也无法将字符串转ascii

### ISSUE THREAD

**Issue by ohmygodlin** [0Chencc/CTFCrackTools#5]
输入A，选Decrypt-》Ascii->Hex，无任何反应。输入41，选Decrypt-》Hex->Ascii，同样无任何反应。

**Comment by ohmygodlin** [comment]
删掉Setting.json重启后又可以了。不知原因。

**Comment by 0Chencc** [comment]
你好，感谢反馈。现在我将工具升级到3.1.2版本，成功修复了这个致命BUG。
[下载地址](https://github.com/0Chencc/CTFCrackTools/releases/tag/3.1.2)
感谢你的反馈

**Comment by 0Chencc** [comment]
你好 关于您之前提交过的部分issue 我已经应用于新版：https://github.com/0Chencc/CTFCrackTools/releases/tag/3.1.4
希望您继续使用后加以反馈，谢谢
