### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by ywsswy** [0Chencc/CTFCrackTools#8]
第三版
HexConvert中应该支持小数部分，目前之能转换整数部分

**Comment by 0Chencc** [comment]
小数的进制转换是属于取余。遇到循环小数会崩，而如果取部分的话又会因为和答案不相符。
所以目前应该不会更新小数的进制转换。
如果需要可以使用python编写一个插件，然后导入到工具里即可。
插件编写在readme.md

**Comment by ywsswy** [comment]
好吧，实际经常会遇到，比如(EF9B.A8)转换成10进制，如果无限循环的话就设置一个位数上限嘛

**Comment by 0Chencc** [comment]
1.进制转换成小数，这个可以实现
2.如果是无限循环，各个题目答案的取值不同。没有一个统一的标准，位数上限不能实现，
