### ISSUE TITLE
培根密码问题

### ISSUE THREAD

**Issue by ywsswy** [0Chencc/CTFCrackTools#9]
培根密码有两种对应方案，而这版本中只有一种，所以会出现解密错误的情况

**Comment by 0Chencc** [comment]
这个问题我上周的时候注意到了，没有及时回复你，见谅：）
我目前在用kotlin重写框架的内核，并且我注意到第一版的培根密码（i=j）的版本已经逐渐被弃用
所以我已经在新的内核内改成第二版，也就是每个字母都有对应的字母表。
发布周期大概还有1-2周。我尽快赶完。
如果急需的话，可以尝试：
1、编写插件：
按照开发文档的格式编写一个新的插件，导入到框架中
2、改目前已有的插件：
目前的版本的培根密码是调用我们团队其他人编写的python脚本，保存的目录是Lib/peigen.py可以找到并更改
